#
# Testcase for root/cimv2:RCP_HttpdSettingData
#
# Generated by 'genprovider' for use with cmpi-bindings-ruby
require 'rubygems'
require 'sfcc'
require 'test/unit'
require 'provider-testing'

class Test_RCP_HttpdSettingData < Test::Unit::TestCase
  def setup
    @client, @op = ProviderTesting.setup 'RCP_HttpdSettingData', 'test/test'
  end
  
  def test_registered
    cimclass = @client.get_class(@op)
    assert cimclass
  end
  
  def test_instance_names
    names = @client.instance_names(@op)
    assert names.size > 0
    names.each do |ref|
      ref.namespace = @op.namespace
      instance = @client.get_instance ref
      assert instance
      
      assert instance.DocumentRoot
      if instance.DocumentRoot
        assert_kind_of String, instance.DocumentRoot # string
      end
      assert instance.Port
      if instance.port
        assert_kind_of Integer, instance.Port # uint16
      end
    end
  end

end
